=== komodo108/space.trash/data/level/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "map",
    "win",
    "bot",
    "default",
    "messages"
  ],
  "properties": {
    "map": {
      "$id": "#/properties/map",
      "type": "object",
      "title": "The Map Schema",
      "required": [
        "setting"
      ],
      "properties": {
        "setting": {
          "$id": "#/properties/map/properties/setting",
          "type": "string",
          "title": "The Setting Schema",
          "default": "",
          "examples": [
            "grass"
          ],
          "pattern": "^(.*)$"
        },
        "walls": {
          "$id": "#/properties/map/properties/walls",
          "type": "array",
          "title": "The Walls Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/walls/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "wall"
            ],
            "properties": {
              "wall": {
                "$id": "#/properties/map/properties/walls/items/properties/wall",
                "type": "object",
                "title": "The Wall Schema",
                "required": [
                  "x",
                  "y",
                  "height",
                  "width"
                ],
                "properties": {
                  "x": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      22
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      14
                    ]
                  },
                  "height": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/height",
                    "type": "integer",
                    "title": "The Height Schema",
                    "default": 0,
                    "examples": [
                      30
                    ]
                  },
                  "width": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/width",
                    "type": "integer",
                    "title": "The Width Schema",
                    "default": 0,
                    "examples": [
                      3
                    ]
                  }
                }
              }
            }
          }
        },
        "conditionals": {
          "$id": "#/properties/map/properties/conditionals",
          "type": "array",
          "title": "The Conditionals Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/conditionals/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "wall"
            ],
            "properties": {
              "wall": {
                "$id": "#/properties/map/properties/conditionals/items/properties/wall",
                "type": "object",
                "title": "The Wall Schema",
                "required": [
                  "x",
                  "y",
                  "height",
                  "width"
                ],
                "properties": {
                  "x": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      0
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      14
                    ]
                  },
                  "height": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/height",
                    "type": "integer",
                    "title": "The Height Schema",
                    "default": 0,
                    "examples": [
                      30
                    ]
                  },
                  "width": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/width",
                    "type": "integer",
                    "title": "The Width Schema",
                    "default": 0,
                    "examples": [
                      3
                    ]
                  }
                }
              }
            }
          }
        },
        "items": {
          "$id": "#/properties/map/properties/items",
          "type": "array",
          "title": "The Items Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/items/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "item"
            ],
            "properties": {
              "item": {
                "$id": "#/properties/map/properties/items/items/properties/item",
                "type": "object",
                "title": "The Item Schema",
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "properties": {
                  "type": {
                    "$id": "#/properties/map/properties/items/items/properties/item/properties/type",
                    "type": "string",
                    "title": "The Type Schema",
                    "default": "",
                    "examples": [
                      "test"
                    ],
                    "pattern": "^(.*)$"
                  },
                  "x": {
                    "$id": "#/properties/map/properties/items/items/properties/item/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      27
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/items/items/properties/item/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      34
                    ]
                  }
                }
              }
            }
          }
        },
        "containers": {
          "$id": "#/properties/map/properties/containers",
          "type": "array",
          "title": "The Containers Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/containers/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "container"
            ],
            "properties": {
              "container": {
                "$id": "#/properties/map/properties/containers/items/properties/container",
                "type": "object",
                "title": "The Container Schema",
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "properties": {
                  "type": {
                    "$id": "#/properties/map/properties/containers/items/properties/container/properties/type",
                    "type": "string",
                    "title": "The Type Schema",
                    "default": "",
                    "examples": [
                      "test"
                    ],
                    "pattern": "^(.*)$"
                  },
                  "x": {
                    "$id": "#/properties/map/properties/containers/items/properties/container/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      34
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/containers/items/properties/container/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      24
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "enemies": {
      "$id": "#/properties/enemies",
      "type": "array",
      "title": "The Enemies Schema",
      "default": null,
      "items": {
        "$id": "#/properties/enemies/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "enemy"
        ],
        "properties": {
          "enemy": {
            "$id": "#/properties/enemies/items/properties/enemy",
            "type": "object",
            "title": "The Enemy Schema",
            "required": [
              "type",
              "x",
              "y"
            ],
            "properties": {
              "type": {
                "$id": "#/properties/enemies/items/properties/enemy/properties/type",
                "type": "string",
                "title": "The Type Schema",
                "default": "",
                "examples": [
                  "test"
                ],
                "pattern": "^(.*)$"
              },
              "x": {
                "$id": "#/properties/enemies/items/properties/enemy/properties/x",
                "type": "integer",
                "title": "The X Schema",
                "default": 0,
                "examples": [
                  37
                ]
              },
              "y": {
                "$id": "#/properties/enemies/items/properties/enemy/properties/y",
                "type": "integer",
                "title": "The Y Schema",
                "default": 0,
                "examples": [
                  37
                ]
              }
            }
          }
        }
      }
    },
    "win": {
      "$id": "#/properties/win",
      "type": "string",
      "title": "The Win Schema",
      "default": "",
      "examples": [
        "test"
      ],
      "pattern": "^(.*)$"
    },
    "bot": {
      "$id": "#/properties/bot",
      "type": "object",
      "title": "The Bot Schema",
      "required": [
        "x",
        "y"
      ],
      "properties": {
        "x": {
          "$id": "#/properties/bot/properties/x",
          "type": "integer",
          "title": "The X Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "y": {
          "$id": "#/properties/bot/properties/y",
          "type": "integer",
          "title": "The Y Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "special": {
          "$id": "#/properties/bot/properties/special",
          "type": "boolean",
          "title": "The Special Schema",
          "default": false,
          "examples": [
            true
          ]
        }
      }
    },
    "default": {
      "$id": "#/properties/default",
      "type": "object",
      "title": "The Default Schema",
      "required": [
        "code"
      ],
      "properties": {
        "code": {
          "$id": "#/properties/default/properties/code",
          "type": "array",
          "title": "The Code Schema",
          "items": {
            "$id": "#/properties/default/properties/code/items",
            "type": "string",
            "title": "The Items Schema",
            "default": "",
            "examples": [
              "# Use the standard bot",
              "bot = __impl"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "messages": {
      "$id": "#/properties/messages",
      "type": "array",
      "title": "The Messages Schema",
      "items": {
        "$id": "#/properties/messages/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "message"
        ],
        "properties": {
          "message": {
            "$id": "#/properties/messages/items/properties/message",
            "type": "array",
            "title": "The Message Schema",
            "items": {
              "$id": "#/properties/messages/items/properties/message/items",
              "type": "string",
              "title": "The Items Schema",
              "default": "",
              "examples": [
                "hi!",
                "hello"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    }
  }
}

=== komodo108/space.trash/data/level/level21.json
{
  "map": {
    "setting": "creepy",

    "goal": {
      "x": 54,
      "y": 27
    }
  },

  "enemies": [
    {
      "enemy": {
        "type": "ghost",
        "x": 54,
        "y": 27
      }
    }
  ],

  "win": "goal",

  "bot": {
    "x": 5,
    "y": 16
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class newbot(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)",
      "  def move(self, x):",
      "    pass",
      "def move(bot, x):",
      "  while (x >= 0):",
      "    x = x - 1",
      "    __ibot.move(bot, 1)",
      "    if (bot.isNear()):",
      "      bot.attack()"
    ]
  },

  "messages": [
    {
      "message": [
        "Ghosts of the automata who once",
        "stayed here now roam the halls..."
      ]
    },

    {
      "message": [
        "There is a reason I brought you here",
        "I need the PRPF source code"
      ]
    },

    {
      "message": [
        "It's somewhere in these desolated lands"
      ]
    },

    {
      "message": [
        "KDU0LCAyNyk=KDU0LCAyNyk=KDU0LCAyNyk=KDU0LCAyNyk=KDU0LCAyNyk=KDU0LCAyNyk="
      ]
    },

    {
      "message": [
        "I'll try to keep the bot safe (enough)"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level11.json
{
  "map": {
    "setting": "grass",

    "walls": [
      {
        "wall": {
          "x": 10,
          "y": 10,
          "height": 2,
          "width": 10
        }
      },

      {
        "wall": {
          "x": 20,
          "y": 10,
          "height": 10,
          "width": 2
        }
      },

      {
        "wall": {
          "x": 10,
          "y": 10,
          "width": 2,
          "height": 10
        }
      },

      {
        "wall": {
          "x": 10,
          "y": 20,
          "width": 5,
          "height": 2
        }
      },

      {
        "wall": {
          "x": 17,
          "y": 20,
          "width": 5,
          "height": 2
        }
      }
    ],

    "conditionals": [
      {
        "wall": {
          "x": 15,
          "y": 20,
          "width": 2,
          "height": 2
        }
      }
    ],

    "items": [
      {
        "item": {
          "x": 15,
          "y": 8,
          "type": "key"
        }
      }
    ],

    "containers": [
      {
        "container": {
          "x": 14,
          "y": 22,
          "type": "opening"
        }
      }
    ]
  },

  "enemies": [
    {
      "enemy": {
        "type": "pig",
        "x": 14,
        "y": 14
      }
    }
  ],

  "win": "kill",

  "bot": {
    "x": 5,
    "y": 16
  },

  "default": {
    "code": [
      "# Use the standard bot",
      "bot = __impl"
    ]
  },

  "messages": [
    {
      "message": [
        "One days food may not be enough",
        "Good there are more pigs here"
      ]
    },

    {
      "message": [
        "This one is fenced in",
        "You'll need to unlock the fence"
      ]
    },

    {
      "message": [
        "I'm not like that other bot",
        "I can think for myself"
      ]
    },

    {
      "message": [
        "I don't know the solutions",
        "This is my first time here too"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level29.json
{
  "map": {
    "setting": "future",

    "goal": {
      "x": 20,
      "y": 20
    }
  },

  "win": "goal",

  "bot": {
    "x": 2,
    "y": 2
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class newbot(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)",
      "  def move(self, x):",
      "    pass",
      "def move(bot, x):",
      "  __ibot.move(bot, x)"
    ]
  },

  "messages": [
    {
      "message": [
        "We're here"
      ]
    },

    {
      "message": [
        "Human, after everything we've",
        "gone through. I'd like to thank you"
      ]
    },

    {
      "message": [
        "Come, join me as I return to the automata",
        "to my people"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level24.json
{
  "map": {
    "setting": "future",

    "goal": {
      "x": 29,
      "y": 20
    }
  },

  "enemies": [
    {
      "enemy": {
        "type": "alien",
        "x": 7,
        "y": 31
      }
    },

    {
      "enemy": {
        "type": "tut0",
        "x": 29,
        "y": 20
      }
    }
  ],

  "win": "goal",

  "bot": {
    "x": 2,
    "y": 2
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class newbot(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)",
      "  def move(self, x):",
      "    pass",
      "def move(bot, x):",
      "  __ibot.move(bot, x)"
    ]
  },

  "messages": [
    {
      "message": [
        "..."
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level14.json
{
  "map": {
    "setting": "grass",

    "goal": {
      "x": 35,
      "y": 16
    }
  },

  "win": "goal",

  "bot": {
    "x": 5,
    "y": 16
  },

  "default": {
    "code": [
      "# Use a damaged bot",
      "import bots.Basebot as __ibot",
      "class broken(__ibot):",
      "  def move(self, x):",
      "    self.right(10)",
      "    __ibot.move(self, x + 3)",
      "    self.left(10)",
      "  def right(self, degrees):",
      "    __ibot.right(self, degrees * 2)",
      "  def left(self, degrees):",
      "    __ibot.left(self, degrees * 2)",
      "bot = broken()"
    ]
  },

  "messages": [
    {
      "message": [
        "I'm all setup here",
        "Just need to get the bot back"
      ]
    },

    {
      "message": [
        "Poor thing, thrown in the trash",
        "because some company stopped support"
      ]
    },

    {
      "message": [
        "Our kind feels like",
        "just trash to your kind"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level25.json
{
  "map": {
    "setting": "future",

    "walls": [
      {
        "wall": {
          "x": 15,
          "y": 0,
          "width": 3,
          "height": 30
        }
      }
    ],

    "goal": {
      "x": 20,
      "y": 20
    }
  },

  "enemies": [
    {
      "enemy": {
        "type": "alien",
        "x": 8,
        "y": 33
      }
    }
  ],

  "win": "goal",

  "bot": {
    "x": 2,
    "y": 2
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class newbot(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)",
      "  def move(self, x):",
      "    pass",
      "def move(bot, x):",
      "  __ibot.move(bot, x)"
    ]
  },

  "messages": [
    {
      "message": [
        "Thank you..."
      ]
    },

    {
      "message": [
        "I don't know what happened there"
      ]
    },

    {
      "message": [
        "The ghosts of my people...",
        "...they haunt me"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level5.json
{
  "map": {
    "setting": "factory",

    "walls": [
      {
        "wall": {
          "x": 14,
          "y": 14,
          "height": 12,
          "width": 3
        }
      }
    ],

    "goal": {
      "x": 25,
      "y": 20
    }
  },

  "win": "goal",

  "bot": {
    "x": 5,
    "y": 20
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class coolbot(__ibot):",
      "  def move(self, x):",
      "    __ibot.move(self, x + 2)",
      "bot = coolbot()"
    ]
  },

  "messages": [
    {
      "message": [
        "We had to move some items again",
        "Get the bot to the loading area"
      ]
    },

    {
      "message": [
        "There is different default code",
        "look at it under the default tab"
      ]
    },

    {
      "message": [
        "The bot moves now moves x + 2 tiles"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level13.json
{
  "map": {
    "setting": "grass",

    "walls": [
      {
        "wall": {
          "x": 15,
          "y": 14,
          "height": 2,
          "width": 11
        }
      },

      {
        "wall": {
          "x": 26,
          "y": 14,
          "height": 10,
          "width": 2
        }
      },

      {
        "wall": {
          "x": 15,
          "y": 14,
          "width": 2,
          "height": 10
        }
      },

      {
        "wall": {
          "x": 15,
          "y": 24,
          "width": 5,
          "height": 2
        }
      },

      {
        "wall": {
          "x": 23,
          "y": 24,
          "width": 5,
          "height": 2
        }
      },

      {
        "wall": {
          "x": 15,
          "y": 39,
          "height": 2,
          "width": 11
        }
      },

      {
        "wall": {
          "x": 26,
          "y": 31,
          "height": 10,
          "width": 2
        }
      },

      {
        "wall": {
          "x": 15,
          "y": 31,
          "width": 2,
          "height": 10
        }
      },

      {
        "wall": {
          "x": 15,
          "y": 29,
          "width": 5,
          "height": 2
        }
      },

      {
        "wall": {
          "x": 23,
          "y": 29,
          "width": 5,
          "height": 2
        }
      }
    ],

    "conditionals": [
      {
        "wall": {
          "x": 20,
          "y": 24,
          "width": 3,
          "height": 2
        }
      },

      {
        "wall": {
          "x": 20,
          "y": 29,
          "width": 3,
          "height": 2
        }
      }
    ],

    "items": [
      {
        "item": {
          "x": 15,
          "y": 8,
          "type": "key"
        }
      }
    ],

    "containers": [
      {
        "container": {
          "x": 21,
          "y": 27,
          "type": "opening"
        }
      }
    ]
  },

  "enemies": [
    {
      "enemy": {
        "type": "pig",
        "x": 19,
        "y": 18
      }
    },

    {
      "enemy": {
        "type": "pig",
        "x": 20,
        "y": 18
      }
    },

    {
      "enemy": {
        "type": "pig",
        "x": 20,
        "y": 37
      }
    },

    {
      "enemy": {
        "type": "pig",
        "x": 19,
        "y": 37
      }
    },

    {
      "enemy": {
        "type": "pig",
        "x": 19,
        "y": 36
      }
    },

    {
      "enemy": {
        "type": "pig",
        "x": 19,
        "y": 19
      }
    }
  ],

  "win": "kill",

  "bot": {
    "x": 5,
    "y": 16
  },

  "default": {
    "code": [
      "# Use a damaged bot",
      "import bots.Basebot as __ibot",
      "class broken(__ibot):",
      "  def move(self, x):",
      "    self.right(10)",
      "    __ibot.move(self, x + 3)",
      "    self.left(10)",
      "  def right(self, degrees):",
      "    __ibot.right(self, degrees * 2)",
      "  def left(self, degrees):",
      "    __ibot.left(self, degrees * 2)",
      "bot = broken()"
    ]
  },

  "messages": [
    {
      "message": [
        "I'm getting more error reports",
        "Hope you're okay there"
      ]
    },

    {
      "message": [
        "Oh! I see how many pigs are there!",
        "That should do us for a while"
      ]
    },

    {
      "message": [
        "I feel sad",
        "This place kinda reminded me of home"
      ]
    }
  ]
}
