=== komodo108/space.trash/data/level/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "map",
    "win",
    "bot",
    "default",
    "messages"
  ],
  "properties": {
    "map": {
      "$id": "#/properties/map",
      "type": "object",
      "title": "The Map Schema",
      "required": [
        "setting"
      ],
      "properties": {
        "setting": {
          "$id": "#/properties/map/properties/setting",
          "type": "string",
          "title": "The Setting Schema",
          "default": "",
          "examples": [
            "grass"
          ],
          "pattern": "^(.*)$"
        },
        "walls": {
          "$id": "#/properties/map/properties/walls",
          "type": "array",
          "title": "The Walls Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/walls/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "wall"
            ],
            "properties": {
              "wall": {
                "$id": "#/properties/map/properties/walls/items/properties/wall",
                "type": "object",
                "title": "The Wall Schema",
                "required": [
                  "x",
                  "y",
                  "height",
                  "width"
                ],
                "properties": {
                  "x": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      22
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      14
                    ]
                  },
                  "height": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/height",
                    "type": "integer",
                    "title": "The Height Schema",
                    "default": 0,
                    "examples": [
                      30
                    ]
                  },
                  "width": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/width",
                    "type": "integer",
                    "title": "The Width Schema",
                    "default": 0,
                    "examples": [
                      3
                    ]
                  }
                }
              }
            }
          }
        },
        "conditionals": {
          "$id": "#/properties/map/properties/conditionals",
          "type": "array",
          "title": "The Conditionals Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/conditionals/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "wall"
            ],
            "properties": {
              "wall": {
                "$id": "#/properties/map/properties/conditionals/items/properties/wall",
                "type": "object",
                "title": "The Wall Schema",
                "required": [
                  "x",
                  "y",
                  "height",
                  "width"
                ],
                "properties": {
                  "x": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      0
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      14
                    ]
                  },
                  "height": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/height",
                    "type": "integer",
                    "title": "The Height Schema",
                    "default": 0,
                    "examples": [
                      30
                    ]
                  },
                  "width": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/width",
                    "type": "integer",
                    "title": "The Width Schema",
                    "default": 0,
                    "examples": [
                      3
                    ]
                  }
                }
              }
            }
          }
        },
        "items": {
          "$id": "#/properties/map/properties/items",
          "type": "array",
          "title": "The Items Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/items/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "item"
            ],
            "properties": {
              "item": {
                "$id": "#/properties/map/properties/items/items/properties/item",
                "type": "object",
                "title": "The Item Schema",
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "properties": {
                  "type": {
                    "$id": "#/properties/map/properties/items/items/properties/item/properties/type",
                    "type": "string",
                    "title": "The Type Schema",
                    "default": "",
                    "examples": [
                      "test"
                    ],
                    "pattern": "^(.*)$"
                  },
                  "x": {
                    "$id": "#/properties/map/properties/items/items/properties/item/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      27
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/items/items/properties/item/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      34
                    ]
                  }
                }
              }
            }
          }
        },
        "containers": {
          "$id": "#/properties/map/properties/containers",
          "type": "array",
          "title": "The Containers Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/containers/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "container"
            ],
            "properties": {
              "container": {
                "$id": "#/properties/map/properties/containers/items/properties/container",
                "type": "object",
                "title": "The Container Schema",
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "properties": {
                  "type": {
                    "$id": "#/properties/map/properties/containers/items/properties/container/properties/type",
                    "type": "string",
                    "title": "The Type Schema",
                    "default": "",
                    "examples": [
                      "test"
                    ],
                    "pattern": "^(.*)$"
                  },
                  "x": {
                    "$id": "#/properties/map/properties/containers/items/properties/container/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      34
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/containers/items/properties/container/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      24
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "enemies": {
      "$id": "#/properties/enemies",
      "type": "array",
      "title": "The Enemies Schema",
      "default": null,
      "items": {
        "$id": "#/properties/enemies/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "enemy"
        ],
        "properties": {
          "enemy": {
            "$id": "#/properties/enemies/items/properties/enemy",
            "type": "object",
            "title": "The Enemy Schema",
            "required": [
              "type",
              "x",
              "y"
            ],
            "properties": {
              "type": {
                "$id": "#/properties/enemies/items/properties/enemy/properties/type",
                "type": "string",
                "title": "The Type Schema",
                "default": "",
                "examples": [
                  "test"
                ],
                "pattern": "^(.*)$"
              },
              "x": {
                "$id": "#/properties/enemies/items/properties/enemy/properties/x",
                "type": "integer",
                "title": "The X Schema",
                "default": 0,
                "examples": [
                  37
                ]
              },
              "y": {
                "$id": "#/properties/enemies/items/properties/enemy/properties/y",
                "type": "integer",
                "title": "The Y Schema",
                "default": 0,
                "examples": [
                  37
                ]
              }
            }
          }
        }
      }
    },
    "win": {
      "$id": "#/properties/win",
      "type": "string",
      "title": "The Win Schema",
      "default": "",
      "examples": [
        "test"
      ],
      "pattern": "^(.*)$"
    },
    "bot": {
      "$id": "#/properties/bot",
      "type": "object",
      "title": "The Bot Schema",
      "required": [
        "x",
        "y"
      ],
      "properties": {
        "x": {
          "$id": "#/properties/bot/properties/x",
          "type": "integer",
          "title": "The X Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "y": {
          "$id": "#/properties/bot/properties/y",
          "type": "integer",
          "title": "The Y Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "special": {
          "$id": "#/properties/bot/properties/special",
          "type": "boolean",
          "title": "The Special Schema",
          "default": false,
          "examples": [
            true
          ]
        }
      }
    },
    "default": {
      "$id": "#/properties/default",
      "type": "object",
      "title": "The Default Schema",
      "required": [
        "code"
      ],
      "properties": {
        "code": {
          "$id": "#/properties/default/properties/code",
          "type": "array",
          "title": "The Code Schema",
          "items": {
            "$id": "#/properties/default/properties/code/items",
            "type": "string",
            "title": "The Items Schema",
            "default": "",
            "examples": [
              "# Use the standard bot",
              "bot = __impl"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "messages": {
      "$id": "#/properties/messages",
      "type": "array",
      "title": "The Messages Schema",
      "items": {
        "$id": "#/properties/messages/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "message"
        ],
        "properties": {
          "message": {
            "$id": "#/properties/messages/items/properties/message",
            "type": "array",
            "title": "The Message Schema",
            "items": {
              "$id": "#/properties/messages/items/properties/message/items",
              "type": "string",
              "title": "The Items Schema",
              "default": "",
              "examples": [
                "hi!",
                "hello"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    }
  }
}

=== komodo108/space.trash/data/level/level1.json
{
  "map": {
    "setting": "factory",

    "goal": {
      "x": 25,
      "y": 25
    }
  },

  "win": "goal",

  "bot": {
    "x": 5,
    "y": 20
  },

  "default": {
    "code": [
      "# Use the standard bot",
      "bot = __impl"
    ]
  },

  "messages": [
    {
      "message": [
        "Move the bot to the loading area",
        "Click on me if you need help"
      ]
    },

    {
      "message": [
        "Bots can change direction with",
        "bot.left(degrees) or bot.right(degrees)"
      ]
    },

    {
      "message": [
        "The bot will turn left or right",
        "from its facing direction by that many degrees"
      ]
    },

    {
      "message": [
        "After turing the bot can move again"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level6.json
{
  "map": {
    "setting": "factory",

    "walls": [
      {
        "wall": {
          "x": 14,
          "y": 14,
          "height": 12,
          "width": 3
        }
      }
    ],

    "goal": {
      "x": 25,
      "y": 20
    }
  },

  "win": "goal",

  "bot": {
    "x": 5,
    "y": 20
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class coolbot(__ibot):",
      "  def __init__(self, angle):",
      "    __ibot.__init__(self)",
      "    self.angle = angle",
      "  def left(self, degrees):",
      "    pass",
      "  def right(self, degrees):",
      "    pass",
      "  def left(self):",
      "    __ibot.left(self, self.angle)",
      "  def right(self):",
      "    __ibot.right(self, self.angle)"
    ]
  },

  "messages": [
    {
      "message": [
        "Get the bot to the loading area"
      ]
    },

    {
      "message": [
        "There is no bot object made for you",
        "You'll need to make one yourself"
      ]
    },

    {
      "message": [
        "The constructor takes an argument",
        "'angle' that will need to be",
        "provided e.g. 'coolbot(3)'"
      ]
    },

    {
      "message": [
        "You are making an instance of a class",
        "so you need to store it in a variable",
        "e.g. 'mybot = coolbot(3)'"
      ]
    },

    {
      "message": [
        "left() & right() now don't take any",
        "parameters. They turn based upon the",
        "'angle' in the constructor"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level2.json
{
  "map": {
    "setting": "factory",

    "walls": [
      {
        "wall": {
          "x": 14,
          "y": 14,
          "height": 12,
          "width": 3
        }
      }
    ],

    "goal": {
      "x": 25,
      "y": 20
    }
  },

  "win": "goal",

  "bot": {
    "x": 5,
    "y": 20
  },

  "default": {
    "code": [
      "# Use the standard bot",
      "bot = __impl"
    ]
  },

  "messages": [
    {
      "message": [
        "We had to move some items for a while",
        "Get the bot to the loading area"
      ]
    },

    {
      "message": [
        "The bot will turn around when it",
        "collides with a wall"
      ]
    },

    {
      "message": [
        "Try to stay away from the wall",
        "9 tiles away from the bot"
      ]
    },

    {
      "message": [
        "Remember, you can move the bot with",
        "bot.move(x) and turn the bot with",
        "bot.left(degrees) & bot.right(degrees)"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level9.json
{
  "map": {
    "setting": "factory",

    "walls": [
      {
        "wall": {
          "x": 14,
          "y": 14,
          "height": 12,
          "width": 3
        }
      }
    ],

    "items": [
      {
        "item": {
          "x": 15,
          "y": 12,
          "type": "key"
        }
      }
    ],

    "goal": {
      "x": 25,
      "y": 20
    }
  },

  "win": "time",

  "bot": {
    "x": 5,
    "y": 20
  },

  "default": {
    "code": [
      "# Use standard bot",
      "bot = __impl"
    ]
  },

  "messages": [
    {
      "message": [
        "What was that?"
      ]
    },

    {
      "message": [
        "Get to the goal with the key"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level15.json
{
  "map": {
    "setting": "mars",

    "items": [
      {
        "item" : {
          "type": "ore",
          "x": 17,
          "y": 34
        }
      },

      {
        "item": {
          "type": "ore",
          "x": 37,
          "y": 19
        }
      }
    ],

    "containers": [
      {
        "container": {
          "type": "refining",
          "x": 30,
          "y": 30
        }
      }
    ]
  },

  "enemies": [
    {
      "enemy": {
        "type": "martian",
        "x": 7,
        "y": 10
      }
    }
  ],

  "win": "get",

  "bot": {
    "x": 2,
    "y": 4
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class coolbot(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)"
    ]
  },

  "messages": [
    {
      "message": [
        "Welp, another problem :(",
        "Seems we are now out of fuel"
      ]
    },

    {
      "message": [
        "I thought I packed 30k dV worth",
        "Oh, that's a 3 not a 3-0"
      ]
    },

    {
      "message": [
        "I have reset the bot fully",
        "Little guy needs to be reprogrammed"
      ]
    },

    {
      "message": [
        "Watch out for the enemies there",
        "They seem less friendly than the pigs"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level18.json
{
  "map": {
    "setting": "mars",

    "walls": [
      {
        "wall": {
          "x": 37,
          "y": 22,
          "width": 2,
          "height": 8
        }
      },

      {
        "wall": {
          "x": 37,
          "y": 28,
          "width": 8,
          "height": 2
        }
      },

      {
        "wall": {
          "x": 43,
          "y": 22,
          "width": 2,
          "height": 8
        }
      }
    ],

    "conditionals": [
      {
        "wall": {
          "x": 39,
          "y": 22,
          "width": 4,
          "height": 2
        }
      }
    ],

    "items": [
      {
        "item" : {
          "type": "ore",
          "x": 9,
          "y": 27
        }
      },

      {
        "item": {
          "type": "ore",
          "x": 31,
          "y": 19
        }
      }
    ],

    "containers": [
      {
        "container": {
          "type": "refining",
          "x": 30,
          "y": 8
        }
      },

      {
        "container": {
          "type": "fuelled",
          "x": 38,
          "y": 20
        }
      }
    ]
  },

  "enemies": [
    {
      "enemy": {
        "type": "martian",
        "x": 17,
        "y": 20
      }
    },

    {
      "enemy": {
        "type": "martian",
        "x": 19,
        "y": 40
      }
    },

    {
      "enemy": {
        "type": "martian",
        "x": 5,
        "y": 28
      }
    },

    {
      "enemy": {
        "type": "martian",
        "x": 47,
        "y": 20
      }
    },

    {
      "enemy": {
        "type": "martian",
        "x": 37,
        "y": 10
      }
    },

    {
      "enemy": {
        "type": "pig",
        "x": 40,
        "y": 25
      }
    },

    {
      "enemy": {
        "type": "pig",
        "x": 41,
        "y": 26
      }
    }
  ],

  "win": "kill",

  "bot": {
    "x": 2,
    "y": 4
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class newbot(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)",
      "  def move(self, x):",
      "    pass",
      "def move(bot, x):",
      "  __ibot.move(bot, x)"
    ]
  },

  "messages": [
    {
      "message": [
        "This mess looks like the work of your",
        "kind. Always so eager to protect what",
        "is theirs"
      ]
    },

    {
      "message": [
        "We need some more food for you",
        "Kill all guards and pigs"
      ]
    },

    {
      "message": [
        "We can probably leave after",
        "I want to show you something",
        "I want to explain who I am"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level0.json
{
  "map": {
    "setting": "factory",

    "goal": {
      "x": 25,
      "y": 20
    }
  },

  "win": "goal",

  "bot": {
    "x": 5,
    "y": 20
  },

  "default": {
    "code": [
      "# Use the standard bot",
      "bot = __impl"
    ]
  },

  "messages": [
    {
      "message": [
        "Move the bot to the loading area",
        "Click on me if you need help"
      ]
    },

    {
      "message": [
        "You can move the bot with bot.move(x)"
      ]
    },

    {
      "message": [
        "The bot moves in the direction it is facing"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level7.json
{
  "map": {
    "setting": "factory",

    "walls": [
      {
        "wall": {
          "x": 14,
          "y": 14,
          "height": 12,
          "width": 3
        }
      },

      {
        "wall": {
          "x": 9,
          "y": 7,
          "height": 3,
          "width": 21
        }
      },

      {
        "wall": {
          "x": 27,
          "y": 10,
          "height": 22,
          "width": 3
        }
      }
    ],

    "goal": {
      "x": 25,
      "y": 20
    }
  },

  "win": "goal",

  "bot": {
    "x": 5,
    "y": 20
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class coolbot(__ibot):",
      "  def __init__(self, steps):",
      "    __ibot.__init__(self)",
      "    self.steps = steps",
      "  def go(self):",
      "    while self.canMove(self.steps):",
      "      __ibot.move(self, self.steps)",
      "  def move(self, x):",
      "    pass"
    ]
  },

  "messages": [
    {
      "message": [
        "Get the bot to the loading area"
      ]
    },

    {
      "message": [
        "The bot's move function has been changed!",
        "It can now only move with the go function",
        "which moves the bot until it can't anymore"
      ]
    },

    {
      "message": [
        "The constructor takes an argument",
        "'angle' that will need to be",
        "provided e.g. 'coolbot(3)'"
      ]
    },

    {
      "message": [
        "The bot doesn't check if there is",
        "a wall in the way, just that there is",
        "not a wall there"
      ]
    },

    {
      "message": [
        "left() & right() remain unchanged"
      ]
    }
  ]
}
