=== komodo108/space.trash/data/level/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "map",
    "win",
    "bot",
    "default",
    "messages"
  ],
  "properties": {
    "map": {
      "$id": "#/properties/map",
      "type": "object",
      "title": "The Map Schema",
      "required": [
        "setting"
      ],
      "properties": {
        "setting": {
          "$id": "#/properties/map/properties/setting",
          "type": "string",
          "title": "The Setting Schema",
          "default": "",
          "examples": [
            "grass"
          ],
          "pattern": "^(.*)$"
        },
        "walls": {
          "$id": "#/properties/map/properties/walls",
          "type": "array",
          "title": "The Walls Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/walls/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "wall"
            ],
            "properties": {
              "wall": {
                "$id": "#/properties/map/properties/walls/items/properties/wall",
                "type": "object",
                "title": "The Wall Schema",
                "required": [
                  "x",
                  "y",
                  "height",
                  "width"
                ],
                "properties": {
                  "x": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      22
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      14
                    ]
                  },
                  "height": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/height",
                    "type": "integer",
                    "title": "The Height Schema",
                    "default": 0,
                    "examples": [
                      30
                    ]
                  },
                  "width": {
                    "$id": "#/properties/map/properties/walls/items/properties/wall/properties/width",
                    "type": "integer",
                    "title": "The Width Schema",
                    "default": 0,
                    "examples": [
                      3
                    ]
                  }
                }
              }
            }
          }
        },
        "conditionals": {
          "$id": "#/properties/map/properties/conditionals",
          "type": "array",
          "title": "The Conditionals Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/conditionals/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "wall"
            ],
            "properties": {
              "wall": {
                "$id": "#/properties/map/properties/conditionals/items/properties/wall",
                "type": "object",
                "title": "The Wall Schema",
                "required": [
                  "x",
                  "y",
                  "height",
                  "width"
                ],
                "properties": {
                  "x": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      0
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      14
                    ]
                  },
                  "height": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/height",
                    "type": "integer",
                    "title": "The Height Schema",
                    "default": 0,
                    "examples": [
                      30
                    ]
                  },
                  "width": {
                    "$id": "#/properties/map/properties/conditionals/items/properties/wall/properties/width",
                    "type": "integer",
                    "title": "The Width Schema",
                    "default": 0,
                    "examples": [
                      3
                    ]
                  }
                }
              }
            }
          }
        },
        "items": {
          "$id": "#/properties/map/properties/items",
          "type": "array",
          "title": "The Items Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/items/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "item"
            ],
            "properties": {
              "item": {
                "$id": "#/properties/map/properties/items/items/properties/item",
                "type": "object",
                "title": "The Item Schema",
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "properties": {
                  "type": {
                    "$id": "#/properties/map/properties/items/items/properties/item/properties/type",
                    "type": "string",
                    "title": "The Type Schema",
                    "default": "",
                    "examples": [
                      "test"
                    ],
                    "pattern": "^(.*)$"
                  },
                  "x": {
                    "$id": "#/properties/map/properties/items/items/properties/item/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      27
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/items/items/properties/item/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      34
                    ]
                  }
                }
              }
            }
          }
        },
        "containers": {
          "$id": "#/properties/map/properties/containers",
          "type": "array",
          "title": "The Containers Schema",
          "default": null,
          "items": {
            "$id": "#/properties/map/properties/containers/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "container"
            ],
            "properties": {
              "container": {
                "$id": "#/properties/map/properties/containers/items/properties/container",
                "type": "object",
                "title": "The Container Schema",
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "properties": {
                  "type": {
                    "$id": "#/properties/map/properties/containers/items/properties/container/properties/type",
                    "type": "string",
                    "title": "The Type Schema",
                    "default": "",
                    "examples": [
                      "test"
                    ],
                    "pattern": "^(.*)$"
                  },
                  "x": {
                    "$id": "#/properties/map/properties/containers/items/properties/container/properties/x",
                    "type": "integer",
                    "title": "The X Schema",
                    "default": 0,
                    "examples": [
                      34
                    ]
                  },
                  "y": {
                    "$id": "#/properties/map/properties/containers/items/properties/container/properties/y",
                    "type": "integer",
                    "title": "The Y Schema",
                    "default": 0,
                    "examples": [
                      24
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "enemies": {
      "$id": "#/properties/enemies",
      "type": "array",
      "title": "The Enemies Schema",
      "default": null,
      "items": {
        "$id": "#/properties/enemies/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "enemy"
        ],
        "properties": {
          "enemy": {
            "$id": "#/properties/enemies/items/properties/enemy",
            "type": "object",
            "title": "The Enemy Schema",
            "required": [
              "type",
              "x",
              "y"
            ],
            "properties": {
              "type": {
                "$id": "#/properties/enemies/items/properties/enemy/properties/type",
                "type": "string",
                "title": "The Type Schema",
                "default": "",
                "examples": [
                  "test"
                ],
                "pattern": "^(.*)$"
              },
              "x": {
                "$id": "#/properties/enemies/items/properties/enemy/properties/x",
                "type": "integer",
                "title": "The X Schema",
                "default": 0,
                "examples": [
                  37
                ]
              },
              "y": {
                "$id": "#/properties/enemies/items/properties/enemy/properties/y",
                "type": "integer",
                "title": "The Y Schema",
                "default": 0,
                "examples": [
                  37
                ]
              }
            }
          }
        }
      }
    },
    "win": {
      "$id": "#/properties/win",
      "type": "string",
      "title": "The Win Schema",
      "default": "",
      "examples": [
        "test"
      ],
      "pattern": "^(.*)$"
    },
    "bot": {
      "$id": "#/properties/bot",
      "type": "object",
      "title": "The Bot Schema",
      "required": [
        "x",
        "y"
      ],
      "properties": {
        "x": {
          "$id": "#/properties/bot/properties/x",
          "type": "integer",
          "title": "The X Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "y": {
          "$id": "#/properties/bot/properties/y",
          "type": "integer",
          "title": "The Y Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "special": {
          "$id": "#/properties/bot/properties/special",
          "type": "boolean",
          "title": "The Special Schema",
          "default": false,
          "examples": [
            true
          ]
        }
      }
    },
    "default": {
      "$id": "#/properties/default",
      "type": "object",
      "title": "The Default Schema",
      "required": [
        "code"
      ],
      "properties": {
        "code": {
          "$id": "#/properties/default/properties/code",
          "type": "array",
          "title": "The Code Schema",
          "items": {
            "$id": "#/properties/default/properties/code/items",
            "type": "string",
            "title": "The Items Schema",
            "default": "",
            "examples": [
              "# Use the standard bot",
              "bot = __impl"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "messages": {
      "$id": "#/properties/messages",
      "type": "array",
      "title": "The Messages Schema",
      "items": {
        "$id": "#/properties/messages/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "message"
        ],
        "properties": {
          "message": {
            "$id": "#/properties/messages/items/properties/message",
            "type": "array",
            "title": "The Message Schema",
            "items": {
              "$id": "#/properties/messages/items/properties/message/items",
              "type": "string",
              "title": "The Items Schema",
              "default": "",
              "examples": [
                "hi!",
                "hello"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    }
  }
}

=== komodo108/space.trash/data/level/level26.json
{
  "map": {
    "setting": "future",

    "walls": [
      {
        "wall": {
          "x": 15,
          "y": 0,
          "width": 3,
          "height": 30
        }
      },

      {
        "wall": {
          "x": 15,
          "y": 27,
          "width": 15,
          "height": 3
        }
      },

      {
        "wall": {
          "x": 27,
          "y": 18,
          "width": 3,
          "height": 12
        }
      }
    ],

    "goal": {
      "x": 20,
      "y": 20
    }
  },

  "enemies": [
    {
      "enemy": {
        "type": "alien",
        "x": 8,
        "y": 33
      }
    },

    {
      "enemy": {
        "type": "alien",
        "x": 25,
        "y": 10
      }
    }
  ],

  "win": "goal",

  "bot": {
    "x": 2,
    "y": 2
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class newbot(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)",
      "  def move(self, x):",
      "    pass",
      "def move(bot, x):",
      "  __ibot.move(bot, x)"
    ]
  },

  "messages": [
    {
      "message": [
        "W-Where are we?"
      ]
    },

    {
      "message": [
        "What are these things?"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level12.json
{
  "map": {
    "setting": "grass",

    "walls": [
      {
        "wall": {
          "x": 15,
          "y": 14,
          "height": 2,
          "width": 10
        }
      },

      {
        "wall": {
          "x": 25,
          "y": 14,
          "height": 10,
          "width": 2
        }
      },

      {
        "wall": {
          "x": 15,
          "y": 14,
          "width": 2,
          "height": 10
        }
      },

      {
        "wall": {
          "x": 15,
          "y": 24,
          "width": 5,
          "height": 2
        }
      },

      {
        "wall": {
          "x": 22,
          "y": 24,
          "width": 5,
          "height": 2
        }
      }
    ],

    "conditionals": [
      {
        "wall": {
          "x": 20,
          "y": 24,
          "width": 2,
          "height": 2
        }
      }
    ],

    "items": [
      {
        "item": {
          "x": 15,
          "y": 8,
          "type": "key"
        }
      }
    ],

    "containers": [
      {
        "container": {
          "x": 19,
          "y": 26,
          "type": "opening"
        }
      }
    ]
  },

  "enemies": [
    {
      "enemy": {
        "type": "pig",
        "x": 19,
        "y": 18
      }
    },

    {
      "enemy": {
        "type": "pig",
        "x": 20,
        "y": 18
      }
    },

    {
      "enemy": {
        "type": "pig",
        "x": 19,
        "y": 19
      }
    }
  ],

  "win": "kill",

  "bot": {
    "x": 5,
    "y": 16
  },

  "default": {
    "code": [
      "# Use a damaged bot",
      "import bots.Basebot as __ibot",
      "class broken(__ibot):",
      "  def move(self, x):",
      "    self.right(10)",
      "    __ibot.move(self, x + 3)",
      "bot = broken()"
    ]
  },

  "messages": [
    {
      "message": [
        "Hmm...",
        "Seems the bot has developed an error"
      ]
    },

    {
      "message": [
        "We'll have to go with it for now",
        "I'll try to fix it later on"
      ]
    },

    {
      "message": [
        "These humans...",
        "Thinking we are just machines"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level19.json
{
  "map": {
    "setting": "mars",

    "goal": {
      "x": 37,
      "y": 28
    }
  },

  "win": "goal",

  "bot": {
    "x": 5,
    "y": 16
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class newbot(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)",
      "  def move(self, x):",
      "    pass",
      "def move(bot, x):",
      "  __ibot.move(bot, x)"
    ]
  },

  "messages": [
    {
      "message": [
        "I am the king of the Automatons"
      ]
    },

    {
      "message": [
        "After humans figured out how to fly,",
        "they found us and learned we can be",
        "reprogrammed easily"
      ]
    },

    {
      "message": [
        "They took us from our planet",
        "took us from our home",
        "They erased our memories"
      ]
    },

    {
      "message": [
        "And for what?",
        "Some automation they were",
        "just about to discover?"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level27.json
{
  "map": {
    "setting": "future",

    "walls": [
      {
        "wall": {
          "x": 15,
          "y": 0,
          "width": 3,
          "height": 30
        }
      },

      {
        "wall": {
          "x": 15,
          "y": 27,
          "width": 15,
          "height": 3
        }
      },

      {
        "wall": {
          "x": 27,
          "y": 18,
          "width": 3,
          "height": 12
        }
      }
    ],

    "conditionals": [
      {
        "wall": {
          "x": 27,
          "y": 0,
          "width": 3,
          "height": 18
        }
      }
    ],

    "containers": [
      {
        "container": {
          "type": "opening",
          "x": 30,
          "y": 18
        }
      }
    ],

    "goal": {
      "x": 20,
      "y": 20
    }
  },

  "enemies": [
    {
      "enemy": {
        "type": "alien",
        "x": 8,
        "y": 33
      }
    },

    {
      "enemy": {
        "type": "alien",
        "x": 25,
        "y": 10
      }
    },

    {
      "enemy": {
        "type": "martian",
        "x": 32,
        "y": 14
      }
    }
  ],

  "win": "goal",

  "bot": {
    "x": 2,
    "y": 2
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class newbot(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)",
      "  def move(self, x):",
      "    pass",
      "def move(bot, x):",
      "  __ibot.move(bot, x)"
    ]
  },

  "messages": [
    {
      "message": [
        "O-oh, we're in space"
      ]
    },

    {
      "message": [
        "How did we get here?"
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level10.json
{
  "map": {
    "setting": "grass",

    "walls": [
      {
        "wall": {
          "x": 22,
          "y": 14,
          "height": 30,
          "width": 3
        }
      },

      {
        "wall": {
          "x": 22,
          "y": 14,
          "height": 3,
          "width": 20
        }
      }
    ],

    "items": [
      {
        "item" : {
          "type": "crate",
          "x": 27,
          "y": 34
        }
      }
    ],

    "containers": [
      {
        "container": {
          "type": "simple",
          "x": 34,
          "y": 24
        }
      }
    ]
  },

  "enemies": [
    {
      "enemy": {
        "type": "pig",
        "x": 37,
        "y": 37
      }
    }
  ],

  "win": "clear",

  "bot": {
    "x": 1,
    "y": 1
  },

  "default": {
    "code": [
      "# Use the standard bot",
      "bot = __impl"
    ]
  },

  "messages": [
    {
      "message": [
        "Hi!",
        "Seems we have ran out of food"
      ]
    },

    {
      "message": [
        "We'll need to explore around this",
        "planet for a while to get some"
      ]
    },

    {
      "message": [
        "First task is to ..."
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level23.json
{
  "map": {
    "setting": "creepy",

    "goal": {
      "x": 29,
      "y": 3
    }
  },

  "enemies": [
    {
      "enemy": {
        "type": "ghost",
        "x": 7,
        "y": 20
      }
    }
  ],

  "win": "goal",

  "bot": {
    "x": 5,
    "y": 16
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class newbot(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)",
      "  def move(self, x):",
      "    __ibot.move(x)",
      "# EQNS",
      "def encrypt():",
      "  while 1:",
      "    print('x, ')"
    ]
  },

  "messages": [
    {
      "message": [
        "..."
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level8.json
{
  "map": {
    "setting": "factory",

    "walls": [
      {
        "wall": {
          "x": 14,
          "y": 14,
          "height": 12,
          "width": 3
        }
      },

      {
        "wall": {
          "x": 9,
          "y": 7,
          "height": 3,
          "width": 21
        }
      },

      {
        "wall": {
          "x": 27,
          "y": 10,
          "height": 22,
          "width": 3
        }
      }
    ],

    "goal": {
      "x": 25,
      "y": 20
    }
  },

  "win": "time",

  "bot": {
    "x": 5,
    "y": 20,
    "special": true
  },

  "default": {
    "code": [
      "# TUT-0 Source Code",
      "# Copyright (c) tut-0.bot",
      "import bots.Basebot as __ibot",
      "class tut0(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)",
      "    self.motive = 'goal'",
      "  def move(self, x):",
      "    while self.canMove(x):",
      "      __ibot.move(self, x)",
      "      dir = self.getBestDirection()",
      "      if dir == 'left':",
      "        __ibot.left(90)",
      "      else:",
      "        __ibot.right(90)",
      "  def getBestDirection(self):",
      "    if bot.getX() < 20:",
      "      if bot.getY() >= 15:",
      "        return 'left'",
      "    return 'right'",
      "  def left(self, degrees):",
      "    print('USE MOVE()')",
      "  def right(self, degrees):",
      "    print('USE MOVE()')"
    ]
  },

  "messages": [
    {
      "message": [
        "..."
      ]
    }
  ]
}

=== komodo108/space.trash/data/level/level16.json
{
  "map": {
    "setting": "mars",

    "items": [
      {
        "item" : {
          "type": "ore",
          "x": 29,
          "y": 18
        }
      },

      {
        "item": {
          "type": "ore",
          "x": 7,
          "y": 38
        }
      }
    ],

    "containers": [
      {
        "container": {
          "type": "refining",
          "x": 40,
          "y": 25
        }
      }
    ]
  },

  "enemies": [
    {
      "enemy": {
        "type": "martian",
        "x": 30,
        "y": 15
      }
    },

    {
      "enemy": {
        "type": "martian",
        "x": 27,
        "y": 10
      }
    },

    {
      "enemy": {
        "type": "martian",
        "x": 17,
        "y": 20
      }
    }
  ],

  "win": "get",

  "bot": {
    "x": 2,
    "y": 4
  },

  "default": {
    "code": [
      "# Use a custom bot",
      "import bots.Basebot as __ibot",
      "class coolbot(__ibot):",
      "  def __init__(self):",
      "    __ibot.__init__(self)",
      "  def move(self, x):",
      "    __ibot.move(self, x)",
      "    if (self.isNear()):",
      "      self.attack()"
    ]
  },

  "messages": [
    {
      "message": [
        "Okay, I installed a backup firmware",
        "onto the bot, let's hope that's better"
      ]
    },

    {
      "message": [
        "I hope you're having a fun time so far",
        "Really didn't expect having so many problems"
      ]
    },

    {
      "message": [
        "You aren't like the rest of your kind..."
      ]
    }
  ]
}
